name: korean_flutter_project
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  intl: ^0.18.0
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSansBold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansMedium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansRegular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
